[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    lovyan03/LovyanGFX@^1.1.16
    lvgl/lvgl@^8.3.11
    beegee-tokyo/DHT sensor library for ESPx@^1.19

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DLV_CONF_INCLUDE_SIMPLE
